### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by vchhasatia** [predict-idlab/trace-updater#3]
Hello trace-updater,

I am confused by license information. It seems that this package is under MIT license. However, in package.json file it says License: imec license. Can you please help me understand?

**Comment by jonasvdd** [comment]
Hi indeed, this license should be `MIT`, thank you for contributing! 🤝 🤗

**Comment by vchhasatia** [comment]
Thank you very much for prompt action!

From: Jonas Van Der Donckt ***@***.***>
Reply-To: predict-idlab/trace-updater ***@***.***>
Date: Wednesday, November 16, 2022 at 1:58 PM
To: predict-idlab/trace-updater ***@***.***>
Cc: "Chhasatia, Viral" ***@***.***>, Author ***@***.***>
Subject: Re: [predict-idlab/trace-updater] License issue (Issue #3)


Hi indeed, this license should be MIT, thank you for contributing! 🤝 🤗
